# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    # routing_loader: false
    view:
        empty_content:  200
        view_response_listener:  true
        failed_validation:  HTTP_BAD_REQUEST
        formats:
            json: true
            xml: true
    body_listener:
        decoders:
            json:  fos_rest.decoder.json
    format_listener:
        rules:
            - { path: '/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true, fallback_format: html }
    exception:
        enabled: true
    serializer:
        serialize_null: true
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }